masto_server: 'https://mastodon.social/'
access_token: 'PASTE_ACCESS_TOKEN_HERE'
thresholds:
    toxicity: 1.0
    severe_toxicity: 0.5
    threat: 0.8
    insult: 0.8
    identity_attack: 0.1
keywords: []
